<?php
use Magento\Framework\App\Action\Action;
$isModuleEnable = $this->helper(\Letscms\BuyNowBtn\Helper\Data::class)->getConfig('LetscmsBuyNowBtn_General/general/enable_status');
$hide_Buy_Now_btn = $this->helper(\Letscms\BuyNowBtn\Helper\Data::class)->getConfig('LetscmsBuyNowBtn_General/general/hide_Buy_Now_btn');
$hideCart = $this->helper(\Letscms\BuyNowBtn\Helper\Data::class)->getConfig('LetscmsBuyNowBtn_General/general/hide_add_to_cart');
$Button_Bg = $this->helper(\Letscms\BuyNowBtn\Helper\Data::class)->getConfig('LetscmsBuyNowBtn_General/general/Button_Bg');
$Button_Color = $this->helper(\Letscms\BuyNowBtn\Helper\Data::class)->getConfig('LetscmsBuyNowBtn_General/general/Button_Color');
$flag = 1;
if ($isModuleEnable):   
endif; ?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
   
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?=   $viewMode ?> products-<?=   $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?=   ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-<?=    $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?=  $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?=   $block->getProductPrice($_product) ?>

                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()):?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?=   $block->escapeHtml($_product->getSku()) ?>"
                                              action="<?=   $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_product) ?>"
                                              id="product_addtocart_form_<?=   $postParams['data']['product']; ?>"
                                              method="post">
                                            <input type="hidden" name="product" value="<?=   $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?=   Action::PARAM_NAME_URL_ENCODED ?>" value="<?=   $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <?php if ($isModuleEnable ? ($hideCart ? $flag = 0 : $flag) : $flag): ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary<?=   $isModuleEnable ? '  Letscms-buynow-custom-tocart' : '' ?>"
                                                >
                                                    <span><?=   __('Add to Cart') ?></span>
                                                </button>
                                            <?php endif; ?>
                                            <?php if ($isModuleEnable):
                                            if ($hide_Buy_Now_btn):
                                                $buttonTitle = $this->helper("Letscms\BuyNowBtn\Helper\Data")->getConfig('LetscmsBuyNowBtn_General/general/button_title');?>
                                                <button type="button"
                                                        title="<?=   $block->escapeHtml(__($buttonTitle)); ?>"
                                                        class="action primary BuyNowBtn Letscms-buynow-button"
                                                        onclick="location.href='<?php echo 'BuyNowBtn/Cart/add' . '?product_id=' . $_product->getId(); ?>'"
                                                >
                                                    <span><?=   __($buttonTitle) ?></span>
                                                </button>
                                            <?php endif; endif; ?>
                                        </form>
                                    <?php else:?>
                                        <?php if ($_product->isAvailable()):?>
                                            <div class="stock available">
                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else:?>
                                            <div class="stock unavailable">
                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                                      $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                    ) : '' ?>
                                <div data-role="add-to-links" class="actions-secondary">
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                                <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                                      $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                    ) : '' ?>
                            </div>
                            <?php if ($showDescription): ?>
                                <div class="product description product-item-description">
                                    <?=   $_helper->productAttribute(
                                        $_product,
                                        $_product->getShortDescription(),
                                        'short_description'
                                    ) ?>
                                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                       title="<?=   $_productNameStripped ?>"
                                       class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?=   $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<style>
    .BuyNowBtn{
  
    background: <?php echo $Button_Bg  ? $Button_Bg  : '#1979c3'; ?>;
    border: 1px solid <?php echo $Button_Bg  ? $Button_Bg  : '#1979c3';  ?>;
    color: <?php echo $Button_Color ? $Button_Color : '#ffff'; ?>;
    cursor: pointer;
    display: inline-block;
    font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 700;
    padding: 7px 15px;
    font-size: 1.4rem;
    box-sizing: border-box;
    vertical-align: middle;       
}
.BuyNowBtn:hover{
    background: <?php echo $Button_Bg  ? $Button_Bg  : '#1979c3'; ?>;
    border: 1px solid <?php echo $Button_Bg  ? $Button_Bg  : '#1979c3';  ?>;
    color: <?php echo $Button_Color ? $Button_Color : '#ffff'; ?>;
}
@media only screen and (max-width: 768px) {
    .BuyNowBtn{
  
 margin: 10px 0px;      
}
}
</style>